### ISSUE TITLE
使用过程的问题about flv frame timestamp

### ISSUE THREAD

**Issue by Polyisoprene** [InJeCTrL/PyLiveRecorder#1]
在实际使用过程中，从开播开始下载视频还好，播放很流畅。但是如果是从直播中间开始下载的话，下载超过一个小时的视频文件，用不同的播放器打开就不一样了，比如我从直播中间录了到直播结束连续总时长约一个半小时的视频，但是直播的总时长是7个多小时，这个时候用potplayer打开FLV文件显示视频总时长1个多小时，而且你还不能跳转播放，一跳转播放瞬间卡死。但是如果我用迅雷下载器自带的播放组件播放的话显示视频时长7个多小时，这个时候可以跳转播放。但是我很确定这个视频的时长只有1个多小时。

**Comment by InJeCTrL** [comment]
由于服务端向客户端推送的flv流中，帧的时间戳很可能会出现异常，一般使用转码工具重新转码（复制音频、视频流）即可修复这一问题。目前的临时解决方法如上，后续我可能会尝试修改脚本，在下载期间就处理时间戳。感谢你的反馈。
