### ISSUE TITLE
关于带密码的直播间的问题

### ISSUE THREAD

**Issue by Polyisoprene** [InJeCTrL/PyLiveRecorder#2]
在哔哩哔哩直播的主播有时候会使用带密码的直播间用来做彩排，在填入这种直播间的ID的时候会报错`Input Id or this module is invalid!
Process finished with exit code 0`。

**Comment by InJeCTrL** [comment]
暂时不考虑录制付费、加密、隐藏、封停的直播间，您可以提供一下付费、加密直播间房间号，后续我将进行测试
