### ISSUE TITLE
getInfo方法无法正确给出监控信息

### ISSUE THREAD

**Issue by Elu-Thingol** [InJeCTrL/PyLiveRecorder#3]
https://github.com/InJeCTrL/PyLiveRecorder/blob/e6b7bce65b095a1b94b2c3db74dd55d4dce159fe/PyLiveRecorder/__init__.py#L245-L261

此处的`locals()`是否更改为`vars(self)`更为妥当

**Comment by InJeCTrL** [comment]
非常感谢您的建议，我即将进行修改，感谢您的支持！
